### ISSUE TITLE
алло я в дубае, я перезвною

### ISSUE THREAD

**Issue by penggrin12** [natsvnxkaze/cardvival#2]
![фото](https://github.com/natsvnxkaze/cardvival/assets/76795163/d87ea515-0304-4f13-ae77-a388a1d0e28f)

**Comment by natsvnxkaze** [comment]
Это не совсем баг, ведь и бревно, и дерево отрисовывают значения снизу себя — из-за этого они сливаются между собой. В дальнейшем это будет изменено, спасибо за замечание!

**Comment by AndreyDaniluk** [comment]
> Это не совсем баг, ведь и бревно, и дерево отрисовывают значения снизу себя — из-за этого они сливаются между собой. В дальнейшем это будет изменено, спасибо за замечание!

Не баг а фича

**Comment by natsvnxkaze** [comment]
> > Это не совсем баг, ведь и бревно, и дерево отрисовывают значения снизу себя — из-за этого они сливаются между собой. В дальнейшем это будет изменено, спасибо за замечание!
> 
> Не баг а фича

всё верно, но в конце концов я это исправил
